language: android

android:
  components:
      - build-tools-21.1.2
      - android-21
      - addon-google_apis-google-21
      - extra-google-m2repository
      - extra-android-m2repository
      - sys-img-armeabi-v7a-addon-google_apis-google-21
